# Generated by Django 6.0 on 2025-12-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('attendants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Animatronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('animal', models.CharField(choices=[('BE', 'Bear'), ('CH', 'Chicken'), ('BU', 'Bunny'), ('FO', 'Fox')], max_length=2)),
                ('build_date', models.DateField()),
                ('decommissioned', models.BooleanField()),
                ('parties', models.ManyToManyField(blank=True, to='freddyapp.party')),
            ],
        ),
    ]
